sudo: false
language: rust
rust:
  - stable
  - beta
cache: cargo
jobs:
  allow_failures:
    - rust: beta
  fast_finish: true
script:
  - cargo build --verbose
  - cargo test --lib
  - rustup component add clippy
  - cargo clippy --all-features -- -D warnings --verbose
